/**
 * @fileoverview The business context maps: one HTML file per business context
 * skill, the single source of a synthesis a human browses and an AI reads
 * through `bun run context:map` (scripts/context-map.ts).
 *
 * Principle (`agentic-qa-core/references/skill-scaffold.md` §3): `.context/`
 * holds what a SCRIPT pulls from a source of truth; what an AI SYNTHESIZES
 * lives in a skill. The business maps are synthesis, so each one lives inside
 * its own context skill at `references/<map>.html`, generated by
 * `project-context` and edited section by section afterwards.
 *
 * This module is the ONE list of those skills, shared by the reader, the
 * updater (bootstrap delivery + informational parity rows) and the doctor.
 * Import-closed: node builtins only (AGENTS.md §4.5), so `scripts/` imports it,
 * never the other way round.
 */

import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

export interface BusinessContextSkill {
  /** Skill slug under `.agents/skills/`. */
  slug: string
  /** File name of the map inside the skill's `references/`. */
  map: string
  /** `project-context` mode that generates the map. */
  mode: string
  /** The markdown map this skill replaces, kept in a consumer repo and read as generator input. */
  legacy: string
}

/**
 * Business context skills upstream ships as placeholders. Unlike every other
 * `<aspect>-context` (project-local by construction, `isProjectLocalSkillPath`),
 * the updater DELIVERS each of these once when its folder is absent, then never
 * overwrites or deletes it: the map inside is the project's own synthesis.
 */
export const BUSINESS_CONTEXT_SKILLS: readonly BusinessContextSkill[] = [
  { slug: 'business-data-context', map: 'business-data-map.html', mode: 'data', legacy: '.context/business/business-data-map.md' },
  { slug: 'business-api-context', map: 'business-api-map.html', mode: 'api', legacy: '.context/business/business-api-map.md' },
  { slug: 'business-e2e-context', map: 'business-e2e-map.html', mode: 'e2e', legacy: '.context/business/business-feature-map.md' },
];

export const BUSINESS_CONTEXT_SLUGS: ReadonlySet<string> = new Set(BUSINESS_CONTEXT_SKILLS.map(s => s.slug));

/** Line 1 of a map that has not been generated yet. */
export const PLACEHOLDER_BANNER_PREFIX = '<!-- placeholder:';
/** Line 1 of a generated map. */
export const GENERATED_BANNER_PREFIX = '<!-- generated by project-context';

export function businessContextSkill(slug: string): BusinessContextSkill | undefined {
  return BUSINESS_CONTEXT_SKILLS.find(s => s.slug === slug);
}

/** Repo-relative path of a skill's map, forward slashes. */
export function mapRelPath(skill: BusinessContextSkill, skillsDir = '.agents/skills'): string {
  return `${skillsDir.replace(/\\/g, '/').replace(/\/+$/, '')}/${skill.slug}/references/${skill.map}`;
}

/** True when the HTML is a placeholder map (banner on its first non-empty line). */
export function isPlaceholderMap(html: string): boolean {
  const first = html.replace(/^\uFEFF/, '').trimStart().split(/\r?\n/, 1)[0] ?? '';
  return first.startsWith(PLACEHOLDER_BANNER_PREFIX);
}

export type MapState = 'no-skill' | 'no-map' | 'placeholder' | 'generated';

export interface MapStatus {
  skill: BusinessContextSkill
  state: MapState
  /** The legacy markdown map exists beside a missing or placeholder HTML map. */
  legacyPresent: boolean
}

/** State of every business context map in a repo. Read-only. */
export function businessMapStatuses(repoRoot: string): MapStatus[] {
  return BUSINESS_CONTEXT_SKILLS.map((skill) => {
    const skillDir = join(repoRoot, '.agents', 'skills', skill.slug);
    const mapPath = join(skillDir, 'references', skill.map);
    let state: MapState;
    if (!existsSync(skillDir)) { state = 'no-skill'; }
    else if (!existsSync(mapPath)) { state = 'no-map'; }
    else { state = isPlaceholderMap(readFileSync(mapPath, 'utf8')) ? 'placeholder' : 'generated'; }
    const legacyPresent = state !== 'generated' && existsSync(join(repoRoot, ...skill.legacy.split('/')));
    return { skill, state, legacyPresent };
  });
}

/** One human line per map that still needs generating; empty when every map is generated. */
export function businessMapAdvice(status: MapStatus): string | null {
  if (status.state === 'generated' || status.state === 'no-skill') { return null; }
  const what = status.state === 'no-map' ? 'has no map' : 'holds a placeholder map';
  const legacy = status.legacyPresent
    ? `; your old \`${status.skill.legacy}\` is kept and will be read as input`
    : '';
  return `\`${status.skill.slug}\` ${what}${legacy}: run \`project-context\` mode \`${status.skill.mode}\``;
}
